[robots]
robot-0 ansible_host=52.58.250.240 private_ip=10.0.1.68  robot_id=robot_0
robot-1 ansible_host=51.102.250.20 private_ip=10.0.2.111 robot_id=robot_1
robot-2 ansible_host=54.93.81.91   private_ip=10.0.1.94  robot_id=robot_2

[monitoring]
monitoring ansible_host=52.57.14.33

[fleet:children]
robots
monitoring
